services:
  backend:
    container_name: homie-backend
    image: ghcr.io/stybo/homie/backend:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  frontend:
    container_name: homie-frontend
    image: ghcr.io/stybo/homie/frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
