services:
  app:
    container_name: homie
    image: ghcr.io/stybo/homie:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PROXMOX_TOKEN=${PROXMOX_TOKEN}
