services:
  app:
    container_name: homie
    image: ghcr.io/stybo/homie:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PROXMOX_TOKEN=${PROXMOX_TOKEN}
      - PROXMOX_BASE_URL=${PROXMOX_BASE_URL}
      - PROXMOX_NODE=${PROXMOX_NODE:-homelab}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - MORNING_START_HOUR=${MORNING_START_HOUR}
