minimumReleaseAge: 0

catalogMode: manual

update:
  githubActions: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
    eslint: "10"

allowBuilds:
  "@heroui-pro/react": true
  "@zowe/secrets-for-zowe-sdk": true
  heroui-native-pro: true
  heroui-pro: true
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
