minimumReleaseAge: 0

packages:
  - apps/*
  - packages/*

catalogMode: manual

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@heroui-pro/react": true
  "@sentry/node-cpu-profiler": true
  "@zowe/secrets-for-zowe-sdk": true
  heroui-native-pro: true
  heroui-pro: true
