minimumReleaseAge: 0

packages:
  - apps/*
  - packages/*

catalogMode: manual

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  "@heroui-pro/react": true
  "@sentry/node-cpu-profiler": true
  "@zowe/secrets-for-zowe-sdk": true
  heroui-pro: true
