name: QA

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      HEROUI_AUTH_TOKEN: ${{ secrets.HEROUI_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1.19.0
        with:
          cache: true
          run-install: true

      - name: Check code
        run: vp check
