name: QA

on:
  workflow_call:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      HEROUI_AUTH_TOKEN: ${{ secrets.HEROUI_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          cache: true
          run-install: true

      - name: Check code
        run: vpr check

      - name: Test code
        run: vpr test

      - name: Build code
        run: vpr build
